# Usa una imagen base de Python
FROM python:3.9-slim-buster

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de dependencias y lo instala
COPY requirements-device.txt .
RUN pip install --no-cache-dir -r requirements-device.txt

# Copia el script del simulador
COPY device_simulator.py .

# Comando para ejecutar la aplicación
CMD ["python", "device_simulator.py"]